export enum Cargo {
  ADMINISTRADOR = 'ADMINISTRADOR',
  ASESOR = 'ASESOR',
  ENTREGADOR = 'ENTREGADOR',
  SUPERVISOR = 'SUPERVISOR',
  CONDUCTOR = 'CONDUCTOR',
  SUPERNUMERARIO = 'SUPERNUMERARIO',
  PASANTE_SENA = 'PASANTE_SENA',
  BODEGUERO = 'BODEGUERO',
  DHO = 'DHO',
  LIDER_LOGISTICO = 'LIDER_LOGISTICO',
}


export enum TipoContrato {
  INDEFINIDO = 'INDEFINIDO',
  FIJO = 'FIJO',
  PRESTACION_SERVICIOS = 'PRESTACION_SERVICIOS',
  APRENDIZAJE = 'APRENDIZAJE',
}

export enum CajaCompensacion {
  COMFAMILIAR = 'COMFAMILIAR',
  COMFACA = 'COMFACA', 
}

export enum Eps {
  NUEVA_EPS = 'NUEVA_EPS',
  SANITAS = 'SANITAS',
}

export enum Arl {
  POSITIVA = 'POSITIVA',
}

export enum FondoPensiones {
  PROTECCION = 'PROTECCION',
  PORVENIR = 'PORVENIR',
  COLPENSIONES = 'COLPENSIONES',
}

export enum TipoRetiro {
  VOLUNTARIO = 'VOLUNTARIO',
  TERMINACION_CONTRATO = 'TERMINACION_CONTRATO',
}

export enum TipoCertificado {
  CON_SALARIO = 'CON_SALARIO',
  SIN_SALARIO = 'SIN_SALARIO',
  RETIRO_SALARIO = 'RETIRO_SALARIO',
  RETIRO_SIN_SALARIO = 'RETIRO_SIN_SALARIO',
  PASANTE_SENA = 'PASANTE_SENA',
}

